@GrowthTracking.NotificationServiceSolution.Presentation_HostAddress = http://localhost:5081

GET {{GrowthTracking.NotificationServiceSolution.Presentation_HostAddress}}/weatherforecast/
Accept: application/json

###
