// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PaymentSolution.Domain.Entities;

public partial class Transaction
{
    public Guid TransactionId { get; set; }

    public Guid ParentId { get; set; }

    public Guid BookingId { get; set; }

    public decimal Amount { get; set; }

    public string PaymentMethod { get; set; }

    public string Status { get; set; }

    public DateTime? TransactionDate { get; set; }

    public string? ReferenceCode { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}