// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GrowthTracking.DoctorSolution.Domain.Entities;

public partial class Certificate
{
    public Guid CertificateId { get; set; }

    public Guid DoctorId { get; set; }

    public string CertificateType { get; set; } = null!;

    public string? CertificateNumber { get; set; }

    public string? IssuingAuthority { get; set; }

    public DateOnly? IssueDate { get; set; }

    public DateOnly? ExpiryDate { get; set; }

    public string? DocumentUrl { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Doctor Doctor { get; set; } = null!;
}