// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GrowthTracking.DoctorSolution.Domain.Entities;

public partial class Doctor
{
    public Guid DoctorId { get; set; }

    public string FullName { get; set; } = null!;

    public DateOnly? DateOfBirth { get; set; }

    public string? Gender { get; set; }

    public string? Address { get; set; }

    public string? PhoneNumber { get; set; }

    public string? Specialization { get; set; }

    public int? ExperienceYears { get; set; }

    public string? Workplace { get; set; }

    public string? Biography { get; set; }

    public string? ProfilePhoto { get; set; }

    public decimal? AverageRating { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Credential> Credentials { get; set; } = new List<Credential>();
}