// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace GrowthTracking.DoctorSolution.Domain.Entities;

public partial class IdentityDocument
{
    public Guid DocumentId { get; set; }

    public Guid DoctorId { get; set; }

    public string Type { get; set; } = null!;

    public string DocumentUrl { get; set; } = null!;

    public string Status { get; set; } = null!;

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Doctor Doctor { get; set; } = null!;

    public Guid? VerifiedByAdminId { get; set; } // Add this field
    public string? RejectionReason { get; set; } // Add this field for remarks if rejected

}