// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using GrowthTracking.DoctorSolution.Domain.Entities;
using System;
using System.Collections.Generic;

namespace GrowthTracking.DoctorSolution.Infrastructure.DBContext;

public partial class UserAccount
{
    public Guid UserAccountId { get; set; }

    public string FullName { get; set; } = null!;

    public string Email { get; set; } = null!;

    public string? PasswordHash { get; set; }

    public string? PhoneNumber { get; set; }

    public string Role { get; set; } = null!;

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? IsActive { get; set; }

    public string? ProfilePictureUrl { get; set; }

    public string? Address { get; set; }

    public string? Bio { get; set; }

    public bool? EmailVerified { get; set; }

    public string? VerificationToken { get; set; }

    public string? ResetToken { get; set; }

    public DateTime? ResetTokenExpiry { get; set; }

    public string? Oauth2GoogleId { get; set; }

    public string? Oauth2FacebookId { get; set; }

    public DateTime? LastLoginAt { get; set; }

    public bool? PhoneVerified { get; set; }
}