server:
  port: 8080

spring:
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:luongwinter@gmail.com}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: ${DATABASE_URL:jdbc:sqlserver://mumei;databaseName=SWD_GrowthTrackingSystemDb;trustServerCertificate=true}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 12345

# SMS provider configuration (example for Twilio)
sms:
  provider:
    twilio:
      account-sid: ${TWILIO_ACCOUNT_SID}
      auth-token: ${TWILIO_AUTH_TOKEN}
      from-number: ${TWILIO_PHONE_NUMBER}

# Logging configuration
logging:
  level:
    com.yourcompany.notification: DEBUG

